const ACTION_TYPES = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_SUCCESS: 'AUTH_SUCCESS',



  LOAD_CHAT_LIST_REQUEST:'LOAD_CHAT_LIST_REQUEST',
  LOAD_CHAT_LIST_SUCCESS:'LOAD_CHAT_LIST_SUCCESS',
  LOAD_CHAT_LIST_ERROR:'LOAD_CHAT_LIST_ERROR',

  SELECT_CHAT_ACTION: 'SELECT_CHAT_ACTION',

  SEND_MESSAGE_REQUEST:'SEND_MESSAGE_REQUEST',
  SEND_MESSAGE_SUCCESS:Symbol('SEND_MESSAGE_SUCCESS'),
  SEND_MESSAGE_ERROR:'SEND_MESSAGE_ERROR',

  LOAD_CHAT_MESSAGES_REQUEST: 'LOAD_CHAT_MESSAGES_REQUEST',
  LOAD_CHAT_MESSAGES_SUCCESS: 'LOAD_CHAT_MESSAGES_SUCCESS',
  LOAD_CHAT_MESSAGES_ERROR: 'LOAD_CHAT_MESSAGES_ERROR',

};

export default ACTION_TYPES;