const ACTION_TYPES = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',

  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_SUCCESS: 'AUTH_SUCCESS',


  LOAD_CHAT_LIST_REQUEST: 'LOAD_CHAT_LIST_REQUEST',
  LOAD_CHAT_LIST_SUCCESS: 'LOAD_CHAT_LIST_SUCCESS',
  LOAD_CHAT_LIST_ERROR: 'LOAD_CHAT_LIST_ERROR',

  SELECT_CHAT_ACTION: 'SELECT_CHAT_ACTION',

  SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
  SEND_MESSAGE_SUCCESS: Symbol( 'SEND_MESSAGE_SUCCESS' ),
  SEND_MESSAGE_ERROR: 'SEND_MESSAGE_ERROR',

  LOAD_CHAT_MESSAGES_REQUEST: 'LOAD_CHAT_MESSAGES_REQUEST',
  LOAD_CHAT_MESSAGES_SUCCESS: 'LOAD_CHAT_MESSAGES_SUCCESS',
  LOAD_CHAT_MESSAGES_ERROR: 'LOAD_CHAT_MESSAGES_ERROR',

  LOAD_ALL_CHATS_REQUEST: 'LOAD_ALL_CHATS_REQUEST',
  LOAD_ALL_CHATS_SUCCESS: 'LOAD_ALL_CHATS_SUCCESS',
  LOAD_ALL_CHATS_ERROR: 'LOAD_ALL_CHATS_ERROR',

  LEAVE_CHAT_REQUEST:'LEAVE_CHAT_REQUEST',
  LEAVE_CHAT_SUCCESS:'LEAVE_CHAT_SUCCESS',
  LEAVE_CHAT_ERROR:'LEAVE_CHAT_ERROR',

  JOIN_USER_TO_CHAT_REQUEST:'JOIN_USER_TO_CHAT_REQUEST',
  JOIN_USER_TO_CHAT_SUCCESS:'JOIN_USER_TO_CHAT_SUCCESS',
  JOIN_USER_TO_CHAT_ERROR:'JOIN_USER_TO_CHAT_ERROR',

  GET_NOTIFICATION_SUCCESS:'GET_NOTIFICATION_SUCCESS',
  DELETE_NOTIFICATION_ACTION:'DELETE_NOTIFICATION_ACTION'

};

export default ACTION_TYPES;